---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notes-app
  labels:
    app: notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notes-app
  template:
    metadata:
      labels:
        app: notes-app
    spec:
      containers:
      - name: notes-app
        image: 296654683697.dkr.ecr.ap-south-1.amazonaws.com/java-registry:30
        env:
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          value: "root"
        - name: DB_IP
          value: "mysql-notes" # This should be the name of the Kubernetes service
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: notes-app-lb
spec:
  selector:
    app: notes-app
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080